---
eda_decision_environments:
  - name: Default Decision Environment Test
    description: Default Event-Driven Ansible decision environment for HTS SRE
    organization: HTS SRE
    image_url: registry.redhat.io/ansible-automation-platform-26/de-supported-rhel9:latest
    pull: always