---
- name: Configure Windows workflows in AAP
  hosts: localhost
  connection: localhost
  gather_facts: false

  vars_files:
    - ../workflows/windows.yaml
    - ../group_vars/all.yaml

  roles:
    - infra.aap_configuration.controller_workflow_job_templates