---
- name: Configure credentials in AAP
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - ../credentials/credential_input_sources.yaml
    - ../group_vars/all.yaml

  pre_tasks:
    - name: Load cloud credentials
      ansible.builtin.include_vars:
        file: ../credentials/cloud.yaml
        name: cloud_credentials_config

    - name: Load secret credentials
      ansible.builtin.include_vars:
        file: ../credentials/secrets.yaml
        name: secret_credentials_config

    - name: Load machine credentials
      ansible.builtin.include_vars:
        file: ../credentials/machine.yaml
        name: machine_credentials_config

    - name: Load platform credentials
      ansible.builtin.include_vars:
        file: ../credentials/platform.yaml
        name: platform_credentials_config

    - name: Load scm credentials
      ansible.builtin.include_vars:
        file: ../credentials/scm.yaml
        name: scm_credentials_config

    - name: Combine credential definitions
      ansible.builtin.set_fact:
        controller_credentials: >-
          {{
            cloud_credentials_config.controller_credentials | default([])
            + secret_credentials_config.controller_credentials | default([])
            + machine_credentials_config.controller_credentials | default([])
            + platform_credentials_config.controller_credentials | default([])
            + scm_credentials_config.controller_credentials | default([])
          }}

  roles:
    - infra.aap_configuration.controller_credentials
    - infra.aap_configuration.controller_credential_input_sources