---
- name: Configure EDA projects in AAP
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - ../eda_projects/projects.yaml
    - ../group_vars/all.yaml

  roles:
    - infra.aap_configuration.eda_projects