---
- name: Configure EDA credentials in AAP
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - ../credentials/eda.yaml
    - ../group_vars/all.yaml

  roles:
    - infra.aap_configuration.eda_credentials