---
- name: Configure Linux Azure job templates in AAP
  hosts: localhost
  connection: localhost
  gather_facts: false

  vars_files:
    - ../job_templates/linux_azure.yaml
    - ../group_vars/all.yaml

  roles:
    - infra.aap_configuration.controller_job_templates