---
- name: Configure complete AAP platform as code
  ansible.builtin.import_playbook: configure_organizations.yaml

- name: Configure credential types
  ansible.builtin.import_playbook: configure_credential_types.yaml

- name: Configure credentials
  ansible.builtin.import_playbook: configure_credentials.yaml

- name: Configure projects
  ansible.builtin.import_playbook: configure_projects.yaml

- name: Configure instance groups
  ansible.builtin.import_playbook: configure_instance_groups.yaml

- name: Configure Azure inventory
  ansible.builtin.import_playbook: configure_azure_inventory.yaml

- name: Configure AWS inventory
  ansible.builtin.import_playbook: configure_aws_inventory.yaml

- name: Configure Local inventory
  ansible.builtin.import_playbook: configure_local_inventory.yaml

- name: Configure Linux Azure job templates
  ansible.builtin.import_playbook: configure_linux_azure_job_templates.yaml

- name: Configure Linux AWS job templates
  ansible.builtin.import_playbook: configure_linux_aws_job_templates.yaml

- name: Configure Windows Azure job templates
  ansible.builtin.import_playbook: configure_windows_azure_job_templates.yaml

- name: Configure Windows AWS job templates
  ansible.builtin.import_playbook: configure_windows_aws_job_templates.yaml

- name: Configure platform job templates
  ansible.builtin.import_playbook: configure_platform_job_templates.yaml

- name: Configure Linux workflows
  ansible.builtin.import_playbook: configure_linux_workflows.yaml

- name: Configure Windows workflows
  ansible.builtin.import_playbook: configure_windows_workflows.yaml

- name: Configure EDA credentials
  ansible.builtin.import_playbook: configure_eda_credentials.yaml

- name: Configure EDA decision environments
  ansible.builtin.import_playbook: configure_decision_environments.yaml

- name: Configure EDA event streams
  ansible.builtin.import_playbook: configure_event_streams.yaml

- name: Configure EDA projects
  ansible.builtin.import_playbook: configure_eda_projects.yaml

- name: Configure EDA rulebook activations
  ansible.builtin.import_playbook: configure_rulebook_activations.yaml