---
- name: Configure Windows AWS job templates in AAP
  hosts: localhost
  connection: localhost
  gather_facts: false

  vars_files:
    - ../job_templates/windows_aws.yaml
    - ../group_vars/all.yaml

  roles:
    - infra.aap_configuration.controller_job_templates