---
- name: Configure credential types in AAP
  hosts: localhost
  connection: local
  gather_facts: false

  vars_files:
    - ../credential_types/credential_types.yaml
    - ../group_vars/all.yaml

  roles:
    - infra.aap_configuration.controller_credential_types